### ISSUE TITLE
bad marshaling of args?

### ISSUE THREAD

**Issue by dichro** [mrala/ecobee_prometheus_exporter#1]
Token exchange appears to succeed, but I get a failure for "bad selection match". The error is:

`prometheus_ecobee_1  | DEBUG:urllib3.connectionpool:https://api.ecobee.com:443 "GET /1/thermostat?json=%7B%0A++%22selection%22%3A+%7B%0A++++%22includeEquipmentStatus%22%3A+true%2C%0A++++%22includeRuntime%22%3A+true%2C%0A++++%22includeSensors%22%3A+true%2C%0A++++%22includeWeather%22%3A+true%2C%0A++++%22selectionMatch%22%3A+%22311062148992auxHeat1%2Cfan%22%2C%0A++++%22selectionType%22%3A+%22thermostats%22%0A++%7D%0A%7D HTTP/1.1" 500 None`

Repeating that with curl fails, but grabbing the selectionMatch from the earlier json dump:

`prometheus_ecobee_1  |     "selectionMatch": "311062148992auxHeat1,fan",`

and using it with curl does work. Any idea what might be going on here?

**Comment by dichro** [comment]
Oops, except that I also see 200s coming back for some calls, like this one:

`prometheus_ecobee_1  | DEBUG:urllib3.connectionpool:https://api.ecobee.com:443 "GET /1/thermostat?json=%7B%0A++%22selection%22%3A+%7B%0A++++%22includeEquipmentStatus%22%3A+true%2C%0A++++%22includeRuntime%22%3A+true%2C%0A++++%22includeSensors%22%3A+true%2C%0A++++%22includeWeather%22%3A+true%2C%0A++++%22selectionMatch%22%3A+%22311062148992%22%2C%0A++++%22selectionType%22%3A+%22thermostats%22%0A++%7D%0A%7D HTTP/1.1" 200 None
prometheus_ecobee_1  | Traceback (most recent call last):
prometheus_ecobee_1  |   File "/usr/local/bin/ecobee_exporter", line 11, in <module>
prometheus_ecobee_1  |     load_entry_point('ecobee-exporter==0.1.0', 'console_scripts', 'ecobee_exporter')()
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/ecobee_exporter-0.1.0-py3.7.egg/ecobee_exporter/exporter.py", line 43, in main
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/prometheus_client-0.5.0-py3.7.egg/prometheus_client/registry.py", line 24, in register
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/prometheus_client-0.5.0-py3.7.egg/prometheus_client/registry.py", line 64, in _get_names
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/ecobee_exporter-0.1.0-py3.7.egg/ecobee_exporter/collector.py", line 289, in collect
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/pyecobee-1.2.1-py3.7.egg/pyecobee/service.py", line 367, in request_thermostats
prometheus_ecobee_1  |     return EcobeeService.__process_http_response(response, EcobeeThermostatResponse)
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/pyecobee-1.2.1-py3.7.egg/pyecobee/service.py", line 130, in __process_http_response
prometheus_ecobee_1  |     is_top_level=True)
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/pyecobee-1.2.1-py3.7.egg/pyecobee/utilities.py", line 89, in dictionary_to_object
prometheus_ecobee_1  |     dictionary_to_object(data[key], property_type, response_properties, parent_classes, indent + 4)
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/pyecobee-1.2.1-py3.7.egg/pyecobee/utilities.py", line 138, in dictionary_to_object
prometheus_ecobee_1  |     indent + 8)
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/pyecobee-1.2.1-py3.7.egg/pyecobee/utilities.py", line 89, in dictionary_to_object
prometheus_ecobee_1  |     dictionary_to_object(data[key], property_type, response_properties, parent_classes, indent + 4)
prometheus_ecobee_1  |   File "/usr/local/lib/python3.7/site-packages/pyecobee-1.2.1-py3.7.egg/pyecobee/utilities.py", line 159, in dictionary_to_object
prometheus_ecobee_1  |     generated_code = '{0}={1!r}'.format(parent_classes[-1].attribute_name_map[key], data[key])
prometheus_ecobee_1  | KeyError: 'rawTemperature'`

repeating that call with curl does show a thermostatList[0].runtime.rawTemperature, but that's the only rawTemperature present. I'll go dig around in pyecobee, I guess.

**Comment by mrala** [comment]
@dichro, there's a PR for pyecobee that fixes this: https://github.com/sfanous/Pyecobee/pull/4

I've switched to the fork linked in that PR so the exporter should be working now.
